#!/usr/bin/env python

import os

import littlechef
from littlechef import runner

# github.com/racker/vmrunwrapper
import vmrunwrapper

old_currwd = os.getcwd()
script_location = os.path.dirname(__file__)
repo_location = os.path.dirname(script_location)
os.chdir(repo_location)


def parse_littlechef_config():
    """
    Parse littlechef "config.cfg"
    """
    littlechef.CONFIGFILE = os.path.join(os.path.dirname(__file__),
                                         'config.cfg')
    runner._readconfig()


def start_and_setup_vm():
    wrapper = vmrunwrapper.VmrunWrapper(
        **vmrunwrapper.get_config(os.path.join(script_location,
                                               'vmrunwrapper.conf')))
    if not wrapper.is_running():
        wrapper.start()

    # share directories should be linked in the autoscale-chef repo under
    # the directory name "shared"
    share_directory = os.path.join(repo_location, 'shared')
    shared_folders = os.listdir(share_directory)
    if 'secure' not in shared_folders or 'otter' not in shared_folders:
        raise Exception("'otter' and 'secure' need to be symlinked into "
                        "autoscaling-chef/shared")

    shared_folders = [(os.path.join(share_directory, directory), None)
                      for directory in os.listdir(share_directory)]
    wrapper.share_folders(shared_folders)

    runner.env.host_string = wrapper.host
    runner.env.host = wrapper.host


parse_littlechef_config()
start_and_setup_vm()

runner.role('dev')  # Applies dev role to vmware

os.chdir(old_currwd)
